version: '3'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.7.2
    environment:
      - cluster.name=elasticsearch5-cluster
      - http.host=0.0.0.0
      - network.publish_host=127.0.0.1
      - transport.tcp.port=9700
      - discovery.type=single-node
      - xpack.security.enabled=false
    ports:
      - "9200:9200"

  kibana:
    image: docker.elastic.co/kibana/kibana:6.7.2
    ports:
      - "5601:5601"

  zookeeper:
    image: 'wurstmeister/zookeeper:latest'
    ports:
      - '2181:2181'

  kafka:
    image: 'wurstmeister/kafka:latest'
    depends_on:
      - zookeeper
    ports:
      - '9092:9092'
    environment:
      KAFKA_BROKER_ID: 0
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_CREATE_TOPICS: elastic-topic:6:1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
